<a href="https://colab.research.google.com/github/lokeshneerasa/MACHINE-LEARNING/blob/main/MACHINE_LEARNING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1.Creating array**



In [1]:
import numpy as np
dataset=np.arange(10)
print(dataset)

[0 1 2 3 4 5 6 7 8 9]


# **2.train_test_split(p) function**

In [4]:
#Ex:1
import numpy as np
from sklearn.model_selection import train_test_split
dataset=np.arange(10)
result=train_test_split(dataset)
print(dataset)
print(result)

[0 1 2 3 4 5 6 7 8 9]
[array([9, 4, 5, 3, 6, 1, 7]), array([8, 0, 2])]


In [8]:
#Ex:2
import numpy as np
from sklearn.model_selection import train_test_split
dataset=np.arange(10)
X_train,X_test=train_test_split(dataset)
print(dataset)
print()
print(X_train)
print(X_test)

[0 1 2 3 4 5 6 7 8 9]

[5 9 2 4 8 6 3]
[0 7 1]


In [13]:
#Ex:3
import numpy as np
from sklearn.model_selection import train_test_split
dataset=np.arange(10)
X_train,X_test=train_test_split(dataset,test_size=4)
print(dataset)
print()
print(X_train)
print(X_test)

[0 1 2 3 4 5 6 7 8 9]

[7 1 8 5 3 2]
[9 6 0 4]


In [15]:
#Ex:4
import numpy as np
from sklearn.model_selection import train_test_split
dataset=np.arange(10)
X_train,X_test=train_test_split(dataset,train_size=6)
print(dataset)
print()
print(X_train)
print(X_test)


[0 1 2 3 4 5 6 7 8 9]

[2 8 9 6 5 3]
[0 7 1 4]


In [16]:
#Ex:5
import numpy as np
from sklearn.model_selection import train_test_split
dataset=np.arange(10)
X_train,X_test=train_test_split(dataset,test_size=0.4)
print(dataset)
print()
print(X_train)
print(X_test)


[0 1 2 3 4 5 6 7 8 9]

[3 9 6 5 4 7]
[2 0 8 1]


In [18]:
#Ex:6
import numpy as np
from sklearn.model_selection import train_test_split
dataset=np.arange(10)
X_train,X_test=train_test_split(dataset,train_size=0.5)
print(dataset)
print()
print(X_train)
print(X_test)

[0 1 2 3 4 5 6 7 8 9]

[5 6 1 2 0]
[7 4 9 3 8]


In [20]:
#Ex:7
import numpy as np
from sklearn.model_selection import train_test_split
dataset=np.arange(10)
X_train,X_test=train_test_split(dataset,train_size=4,test_size=4)
print(dataset)
print()
print(X_train)
print(X_test)

[0 1 2 3 4 5 6 7 8 9]

[3 9 2 7]
[1 6 8 5]


In [21]:
#Ex:8 Train and Test size not in given range and gives value error
import numpy as np
from sklearn.model_selection import train_test_split
dataset=np.arange(10)
X_train,X_test=train_test_split(dataset,train_size=6,test_size=10)
print(dataset)
print()
print(X_train)
print(X_test)

ValueError: test_size=10 should be either positive and smaller than the number of samples 10 or a float in the (0, 1) range

In [22]:
#Ex:9 Creating an array and splitting
import numpy as np
dataset=np.arange(20).reshape(2,10)
print(dataset)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [24]:
#Ex:10
import numpy as np
dataset=np.arange(20).reshape(2,10).T
print(dataset)


[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]


In [25]:
#Ex:11
import numpy as np
x=np.arange(20).reshape(2,10).T
y=np.arange(10)
print(x)
print()
print(y)

[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]

[0 1 2 3 4 5 6 7 8 9]


In [26]:
#Ex:12
import numpy as np
from sklearn.model_selection import train_test_split
X=np.arange(20).reshape(2,10).T
y=np.arange(10)
X_train,X_test,y_train,y_test=train_test_split(X,y)
print(X_train)
print()
print(X_test)
print()
print(y_train)
print()
print(y_test)

[[ 6 16]
 [ 4 14]
 [ 0 10]
 [ 3 13]
 [ 1 11]
 [ 8 18]
 [ 9 19]]

[[ 5 15]
 [ 7 17]
 [ 2 12]]

[6 4 0 3 1 8 9]

[5 7 2]


In [31]:
#Ex:13 random_state
import numpy as np
from sklearn.model_selection import train_test_split
X=np.arange(20).reshape(2,10).T
y=np.arange(10)
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0)
print(X_train)
print()
print(X_test)
print()
print(y_train)
print()
print(y_test)



[[ 9 19]
 [ 1 11]
 [ 6 16]
 [ 7 17]
 [ 3 13]
 [ 0 10]
 [ 5 15]]

[[ 2 12]
 [ 8 18]
 [ 4 14]]

[9 1 6 7 3 0 5]

[2 8 4]
